In [5]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../Simple-Liner-Regression/placement.csv')
df.head()

cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [20]:
X = df.iloc[:, 0].values
y = df.iloc[:, -1].values   # use values because i want to use numpy values

In [30]:
class my_linerRegression:
    def __self__(self):
        self.m = None
        self.b = None
        
    def fit(self, X_train, y_train):
        num = 0
        den = 0
        
        for i in range(X_train.shape[0]):
            num = num + ((X_train[i] - X_train.mean()) * (y_train[i] - y_train.mean()))
            den = den + ((X_train[i] - X_train.mean()) * (X_train[i] - X_train.mean()))
        
        self.m = num / den
        
        self.b = y_train.mean() - (self.m * X_train.mean())
        
        print(self.m, self.b)
    
    def predict(self, X_test):
        return self.m * X_test + self.b

In [31]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=2)
X_train.shape, X_test.shape

((160,), (40,))

In [32]:
my_lr = my_linerRegression()

my_lr.fit(X_train=X_train, y_train=y_train)

0.5579519734250721 -0.8961119222429152


## Sklearn lr value

In [18]:
xx = df[['cgpa']]
yy = df[['package']]

xx_train, xx_test, yy_teain, yy_test = train_test_split(xx, yy, test_size=.2, random_state=2)

In [19]:
from sklearn.linear_model import LinearRegression
sk_lr = LinearRegression()
sk_lr.fit(xx_train, yy_teain)

sk_lr.coef_, sk_lr.intercept_

(array([[0.55795197]]), array([-0.89611192]))

## our value and sklearn value are same they use same eqation

In [24]:
X_test[0]

8.58

In [37]:
my_lr.predict(X_test[0])

3.891116009744203

In [39]:
sk_lr.predict(xx_test.iloc[0].values.reshape(1, 1))

c:\Users\Lenovo\anaconda3\envs\torchGPU\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[3.89111601]])

In [42]:
# its use gradient decent algo

from sklearn.linear_model import SGDRegressor

sdg_lr = SGDRegressor()
sdg_lr.fit(xx_train, yy_teain)
sdg_lr.coef_, sdg_lr.intercept_

c:\Users\Lenovo\anaconda3\envs\torchGPU\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


(array([0.43189186]), array([-0.0147854]))